import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ConvexClerkProvider} from "@/components/providers/ConvexClerkProvider";
import {Navbar} from "@/app/navbar";
// import {SignInButton, UserButton} from "@clerk/clerk-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <ConvexClerkProvider>
        {/*<SignedOut>
              <SignInButton/>
          </SignedOut>
          <SignedIn>
              <UserButton/>
          </SignedIn>*/}

        <Navbar/>
        {children}
    </ConvexClerkProvider>
    </body>
    </html>
  );
}
